[package]
name = "markus/platformer"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
rodux = "roblox/rodux@3.0.0"
roact = "roblox/roact@1.4.4"
testez = "roblox/testez@0.4.1"
roact-rodux = "roblox/roact-rodux@0.5.1"

[server-dependencies]